-define(EXPIRES, 3600 * 1000).
-define(TOKEN_URL, "https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential").
-define(GUEST_SERVICE_URL, "https://api.weixin.qq.com/cgi-bin/message/custom/send?access_token=").
